spring:
  cloud:
    config:
      uri: http://CONFIG-SERVER
server:
  port: 8084

logging:
  file:
    name: /Users/ravi/Desktop/logs/user-service/user-service.log

url:
  holiday: http://localhost:8088/holidays
  leave: http://localhost:8086/leave

kafka:
  boot:
    server: localhost:9092
  topic:
    name: myTopic-kafkasender